### ISSUE TITLE
Host app on AWS

### ISSUE THREAD

**Issue by vivanov1410** [makkke/road-so-far#9]
- [x] host website on S3
- [x] use custom domain `app.roadsofar.com`
- [x] enable [cloudfront](http://docs.aws.amazon.com/gettingstarted/latest/swh/getting-started-create-cfdist.html) to speed up website @wasong 
- [x] enable SSL on `app.roadsofar.com` using [let's encrypt](https://www.codeword.xyz/2016/01/06/lets-encrypt-a-static-site-on-amazon-s3/) or [Amazon Certificate Manager](https://aws.amazon.com/certificate-manager/) @wasong

**Comment by wasong** [comment]
Deployed cloudfront distribution on [d2nt91xs73qlbz.cloudfront.net](http://d2nt91xs73qlbz.cloudfront.net)
Route 53 records configured to redirect these urls:
[roadsofar.com](http://roadsofar.com/)
[www.roadsofar.com](http://www.roadsofar.com/)

**Comment by vivanov1410** [comment]
awesome @wasong, can you change it to point to `app.roadsofar.com` and keep `www.roadsofar.com` empty. We are going to put a public site there later.

**Comment by wasong** [comment]
Changed links.
http://app.roadsofar.com/

**Comment by vivanov1410** [comment]
Looks like this one is done, good job @wasong, closing.
